---

# VM hostname (this will be added to the "vm_ip_aliases" list, displayed in your SSH terminal, etc.)
vm_hostname: 'majora-ansible-vagrant'

# List of aliases bound to the Virtual Machine's IP (see "vm_ip")
# If the plugin "vagrant-hostmanager" is installed, these aliases will be added to your "/etc/hosts" file automatically.
# Else, aliases will be displayed in the console during VM provisioning, then it will be up to you to copy/paste this output in your "/etc/hosts" file.
vm_ip_aliases: []

# Shared folders strategy, possible values are 'self' or 'subdirectory'.
# 'self'         => share this project root with the VM (i.e. "Vagrantfile" is shared),
#                   this strategy is perfect to host a single project in your VM (i.e. the vagrant is included in the project)
# 'subdirectory' => share only a subdirectory of this project root (i.e. "Vagrantfile" is not shared),
#                   this strategy is perfect to host multiple projects in your VM (i.e. the vagrant is outside of the projects)
sharing_strategy: 'self'

# Absolute path of this project root on the VM side (used if shared folders strategy is 'self')
sharing_self_absolute_path_in_vm: '/var/www/majora-ansible-vagrant'

# Relative path from this project root to the subdirectory to share (used if shared folders strategy is 'subdirectory')
sharing_subdirectory_relative_path: 'www'

# Absolute path of the shared subdirectory on the VM side (used if shared folders strategy is 'subdirectory')
sharing_subdirectory_absolute_path_in_vm: '/var/www'

# If you set this to false, the "roles" directory won't be (re)downloaded during VM provisioning
install_ansible_roles: true
